---
on:
  push:
    branches: "*"
    tags-ignore:
      - "*"

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.4'
      - run: |
          go test -v ./...
